### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by curioussavage** [jonnyboy0719/Cuberite-Portal#2]
Hi there, I am writing a gui to (optionally) abstract away they ini file in the web admin, however to be honest I have installed the plugin but not tried it out yet, so I don't know what all of the ini keys represent.

Could you write a small readme file with short explanations for each item. This would help me to write good labels for the form fields.

**Comment by jonnyboy0719** [comment]
the ini files are pretty much straight forward :) But I could write a small readme file tomorrow that will document everything about the ini file, and how it works.

**Comment by curioussavage** [comment]
that would be great thanks. I think what is confusing is that there is a "destination" point but also a target field where the other portal is. In the example on the forum it's hard to tell if that is where the player will spawn when the teleport to it because the coordinates don't seem to fit

**Comment by curioussavage** [comment]
reading again in the forum its sounds like the /pdest command lets you set the point it teleports to and I assume that just sets the destination (xyz) in the ini but it seems redundant to have to set a point when you already set a target portal. Is that (or can that) part be optional for when you just want to send a user to an arbitrary location instead of to another portal?

**Comment by jonnyboy0719** [comment]
the destination_\* (X,Y,Z) are the teleport destination, and the target is the name of the portal. And from that target. destination_ is not connected with target.

**Target**
Tries to grab the name of the portal, if the name exist within portals_portals.ini then it will grab the _world_ to check which world it is located on, and then it grabs its _destination_ X, Y & Z. That's basically how it operates.

**Destinations**
This is the teleport/portal exit location, so it knows it should drop you off at this area. else it will just drop you off at the 0,0,0 location if you haven't set a portal destination.
